### ISSUE TITLE
Trouble while making international shipment

### ISSUE THREAD

**Issue by andoni0305** [uh-opensource/node-shipping-fedex#17]
Im still using  sandbox mode ;
Im using the examples to do tests and it works fine but when I try to make an international shipment with the `.ship`  method i get a 'CustomsValue is required' message as response.

I looked in the Fedex api documentation to see where the CustomsValue should be stated; i found multiple ways to state it and tried doing so but always resulted on errors telling me 'One of [keys] is expected'; some of these keys sometimes already being declared in my object.

I dont know if you have any example on international shipments

This is the way im trying to make the request
`fedex.ship({
  RequestedShipment: {
    ShipTimestamp: new Date(date.getTime() + (24*60*60*1000)).toISOString(),
    DropoffType: 'REGULAR_PICKUP',
    ServiceType: 'INTERNATIONAL_ECONOMY',
    PackagingType: 'YOUR_PACKAGING',

    Shipper: {
      Contact: {
        PersonName: 'Sender Name',
        CompanyName: 'Company Name',
        PhoneNumber: '5555555555'
      },
      Address: {
        StreetLines: [
          'Address Line 1'
        ],
        City: 'Collierville',
        StateOrProvinceCode: 'TN',
        PostalCode: '38017',
        CountryCode: 'US'
      }
    },
    Recipient: {
      Contact: {
        PersonName: 'Recipient Name',
        CompanyName: 'Company Receipt Name',
        PhoneNumber: '5555555555'
      },
      Address: {
        StreetLines: [
          'Del Rocio 17'
        ],
        City: 'Santa Catarina',
        StateOrProvinceCode: 'NL',
        PostalCode: '66188',
        CountryCode: 'MX',
        Residential: true
      }
    },
    ShippingChargesPayment: {
      PaymentType: 'SENDER',
      Payor: {
        ResponsibleParty: {
          AccountNumber: fedex.options.account_number
        }
      }
    },
	CustomsClearenceDetail:{
		CustomsValue:30
	},
    LabelSpecification: {
      LabelFormatType: 'COMMON2D',
      ImageType: 'PDF',
      LabelStockType: 'PAPER_4X6'
    },
    PackageCount: '1',
    RequestedPackageLineItems: [{
	  SequenceNumber: 1,
      Weight: {
        Units: 'LB',
        Value: '50.0'
      },
      Dimensions: {
        Length: 108,
        Width: 5,
        Height: 5,
        Units: 'IN'
      }
  	}],
  }
}, function(err, res) {
  if(err) {
    return console.log(util.inspect(err, {depth: null}));
  }

  console.log(util.inspect(res, {depth: null}));

});`

**Comment by indersingh77** [comment]
hi how can i get the pdf label in my folder? I got the success message in terminal.

**Comment by andoni0305** [comment]
On the response obj 
You get it as a base64 string. I use a npm package that transforms base64 strings to any format at the same time that it uploads it to a specified Amazon s3 URL. The npm in using is base64-string-s3
