### ISSUE TITLE
How to create single shipment for multiple packages.

### ISSUE THREAD

**Issue by shefaleechaudhary** [uh-opensource/node-shipping-fedex#18]
Hello,

We are trying to implement fedEx shipment apis using '**node-shipping-fedex**'. We need to create single shipment for multiple package. 

We haved tried it by adding multiple package inside RequestedPackageLineItems.  Got following error. 

Error: **The number of RequestedPackages in the RequestedShipment must be equal to 1** 
Error code - **2463**

**Comment by jjosef** [comment]
Hi there, we don't represent FedEx so if you're getting an error from them you may want to contact FedEx technical support.
