### ISSUE TITLE
Action Required to Update FedEx Web Services WSDL URLs

### ISSUE THREAD

**Issue by nielsrobin** [uh-opensource/node-shipping-fedex#19]
Fedex have updated their WSDL, which has broken some functionality in your package. Specifically processShipment now fails with error:
9006: Unable to invoke method: processShipment. Service is currently unavailable.

http://www.fedex.com/us/developer/announcements.html

Any chance you can fix this? Rather enjoy using this package.

**Comment by jjosef** [comment]
Hi @nielsrobin I have updated this with new WSDLs which seem to be working again. Can you help me verify? We published v0.2.0 on NPM also.

**Comment by nielsrobin** [comment]
Hi @jjosef,

Thanks for looking into it so quickly mate, just tried to run it after updating to v0.2.0 and got this message now:

{ HighestSeverity: 'FAILURE',
  Notifications:
   [ { Severity: 'FAILURE',
       Source: 'ship',
       Code: 'FFFE',
       Message: 'Resources unavailable to service request',
       LocalizedMessage: 'Resources unavailable to service request' } ],
  Version: { ServiceId: 'ship', Major: 21, Intermediate: 0, Minor: 0 } }

**Comment by nielsrobin** [comment]
![failure](https://user-images.githubusercontent.com/1383483/29034368-1a763efc-7b66-11e7-8ebc-6a4a6f92463a.JPG)
Here is the complete soap envelope incase that helps.

**Comment by jjosef** [comment]
Thanks, are you able to get other services to work like Rate?

**Comment by nielsrobin** [comment]
Yes, Rate works.

**Comment by jjosef** [comment]
Ok, I just called Fedex and they are having a known outage for their web services right now. They gave no estimated time for a fix.

**Comment by nielsrobin** [comment]
Alright, thanks man, guess we'll have to try again in a couple of hours.

**Comment by jjosef** [comment]
I think this may have been the issue to begin with, but thanks for bringing the updated WSDLs to our attention :)

**Comment by jjosef** [comment]
I will leave this open for now, please report back if you get it working again

**Comment by nielsrobin** [comment]
Thanks man, it works now, just tested it, so fedex must have gotten their ws up and running again. I guess the updated wsdl was not the root cause after all, but happy you could use it. Thanks for the quick reaction time, much appreciated.
